<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-QQACKJ4" name="Default test" tests="36" failures="3" timestamp="18 Jul 2017 17:26:35 GMT" time="245.129" errors="0">
  <testcase name="cNetLoginScenario" time="11.777" classname="BatchExecution.UpdateVMScenario"/>
  <testcase name="UpdateVM_Dallas_OpenStack_Dev63" time="0.41" classname="BatchExecution.UpdateVMScenario"/>
  <testcase name="UpdateVM_Dallas_OpenStack_Dev59" time="4.891" classname="BatchExecution.UpdateVMScenario"/>
  <testcase name="UpdateVM_Dallas_OpenStack_Dev91" time="0.037" classname="BatchExecution.UpdateVMScenario"/>
  <testcase name="UpdateVM_Dallas_OpenStack_Dev13" time="0.026" classname="BatchExecution.UpdateVMScenario"/>
  <testcase name="UpdateVM_Dallas_OpenStack_Dev83" time="0.097" classname="BatchExecution.UpdateVMScenario"/>
  <testcase name="UpdateVM_Dallas_OpenStack_Dev84" time="0.026" classname="BatchExecution.UpdateVMScenario"/>
  <testcase name="UpdateVM_Dallas_OpenStack_Prod30" time="0.035" classname="BatchExecution.UpdateVMScenario"/>
  <testcase name="UpdateVM_Dallas_OpenStack_Prod32" time="0.028" classname="BatchExecution.UpdateVMScenario"/>
  <testcase name="UpdateVM_Dallas_Azure_Dev63" time="0.018" classname="BatchExecution.UpdateVMScenario"/>
  <testcase name="UpdateVM_Dallas_Azure_Dev59" time="0.028" classname="BatchExecution.UpdateVMScenario"/>
  <testcase name="UpdateVM_Dallas_Azure_Dev91" time="0.02" classname="BatchExecution.UpdateVMScenario"/>
  <testcase name="UpdateVM_Dallas_Azure_Dev13" time="0.02" classname="BatchExecution.UpdateVMScenario"/>
  <testcase name="UpdateVM_Dallas_Azure_Dev83" time="0.015" classname="BatchExecution.UpdateVMScenario"/>
  <testcase name="UpdateVM_Dallas_Azure_Dev84" time="0.022" classname="BatchExecution.UpdateVMScenario"/>
  <testcase name="UpdateVM_Dallas_Azure_PRD30" time="0.014" classname="BatchExecution.UpdateVMScenario"/>
  <testcase name="UpdateVM_Dallas_Azure_PRD32" time="0.014" classname="BatchExecution.UpdateVMScenario"/>
  <testcase name="UpdateVM_NewYork_AWS_Dev63" time="0.011" classname="BatchExecution.UpdateVMScenario"/>
  <testcase name="UpdateVM_NewYork_AWS_Dev59" time="0.012" classname="BatchExecution.UpdateVMScenario"/>
  <testcase name="UpdateVM_NewYork_AWS_Dev91" time="0.023" classname="BatchExecution.UpdateVMScenario"/>
  <testcase name="UpdateVM_NewYork_AWS_Dev84" time="0.013" classname="BatchExecution.UpdateVMScenario"/>
  <testcase name="UpdateVM_NewYork_AWS_Dev13" time="0.012" classname="BatchExecution.UpdateVMScenario"/>
  <testcase name="UpdateVM_NewYork_AWS_Dev83" time="0.017" classname="BatchExecution.UpdateVMScenario"/>
  <testcase name="UpdateVM_NewYork_AWS_PRD30" time="0.039" classname="BatchExecution.UpdateVMScenario"/>
  <testcase name="UpdateVM_NewYork_AWS_PRD32" time="0.032" classname="BatchExecution.UpdateVMScenario"/>
  <testcase name="UpdateVM_NewYork_VMWare_PRD32" time="0.016" classname="BatchExecution.UpdateVMScenario"/>
  <testcase name="UpdateVM_NewYork_VMWare_PRD30" time="0.016" classname="BatchExecution.UpdateVMScenario"/>
  <testcase name="UpdateVM_NewYork_VMWare_Dev83" time="0.067" classname="BatchExecution.UpdateVMScenario"/>
  <testcase name="UpdateVM_NewYork_VMWare_Dev13" time="0.019" classname="BatchExecution.UpdateVMScenario"/>
  <testcase name="UpdateVM_NewYork_VMWare_Dev91" time="0.036" classname="BatchExecution.UpdateVMScenario"/>
  <testcase name="UpdateVM_NewYork_VMWare_Dev59" time="0.064" classname="BatchExecution.UpdateVMScenario"/>
  <testcase name="UpdateVM_NewYork_VMWare_Dev63" time="0.03" classname="BatchExecution.UpdateVMScenario"/>
  <testcase name="UpdateVM_NewYork_Delete_OpenStack_PRD30" time="151.341" classname="BatchExecution.UpdateVMScenario">
    <failure type="atu.testng.reports.exceptions.ATUReporterStepFailedException">
      <![CDATA[[ATU Custom Reporter Step Failed Exception]
	at atu.testng.reports.listeners.ATUReportsListener.onTestSuccess(Unknown Source)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1690)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1670)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- UpdateVM_NewYork_Delete_OpenStack_PRD30 -->
  <testcase name="UpdateVM_NewYork_Delete_OpenStack_DEV83" time="25.194" classname="BatchExecution.UpdateVMScenario">
    <failure type="atu.testng.reports.exceptions.ATUReporterStepFailedException">
      <![CDATA[[ATU Custom Reporter Step Failed Exception]
	at atu.testng.reports.listeners.ATUReportsListener.onTestSuccess(Unknown Source)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1690)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1670)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- UpdateVM_NewYork_Delete_OpenStack_DEV83 -->
  <testcase name="UpdateVM_NewYork_Delete_OpenStack_DEV13" time="24.731" classname="BatchExecution.UpdateVMScenario">
    <failure type="atu.testng.reports.exceptions.ATUReporterStepFailedException">
      <![CDATA[[ATU Custom Reporter Step Failed Exception]
	at atu.testng.reports.listeners.ATUReportsListener.onTestSuccess(Unknown Source)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1690)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1670)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- UpdateVM_NewYork_Delete_OpenStack_DEV13 -->
  <testcase name="cNetLogoutScenario" time="16.481" classname="BatchExecution.UpdateVMScenario"/>
</testsuite> <!-- Default test -->
